[package]
name = "json-value"
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
description = "Helper method to get the josn value"
repository = "https://github.com/notedge/panduck/tree/master/projects/lipsum-cn"
documentation = "https://docs.rs/lipsum-cn"
readme = "../../readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
serde_json = "1.0.74"